domain-events-sqs:
  provider: localstack
  endpoint.url: http://localhost:4566
  queue.name: rp_api_queue
  dlq.name: rp_api_dlq

domain-events-sns:
  provider: localstack

hmpps.sqs:
  reactiveApi: true
  provider: localstack
  queues:
    bulkcomparison:
      queueName: "bulkcomparison"
      dlqName: "bulkcomparison-dlq"
      dlqMaxReceiveCount: 3
      visibilityTimeout: 120

bulk.calculation.process: true
